# Generated by Django 3.2.5 on 2021-07-25 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reddit_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_choice', models.IntegerField(choices=[(1, 'UP'), (2, 'DOWN')])),
                ('original_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_votes', to='reddit_api.comment')),
                ('original_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_votes', to='reddit_api.post')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('original_post', 'owner'), name='sameOwner_samePost_notAllowed'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('original_comment', 'owner'), name='sameOwner_sameComment_notAllowed'),
        ),
    ]
