# Generated by Django 3.2.5 on 2021-07-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_api', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='display_name',
            field=models.CharField(default=models.CharField(max_length=50, unique=True), max_length=50, unique=True),
        ),
    ]
