# Generated by Django 3.2.5 on 2021-07-21 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_api', '0005_alter_subreddit_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subreddit',
            name='display_name',
        ),
    ]
