# Generated by Django 3.2.5 on 2021-07-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_api', '0006_remove_subreddit_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='display_name',
            field=models.CharField(default='temp', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
