# Generated by Django 3.2.5 on 2021-07-21 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_api', '0008_post_sametitle_in_samesubreddit_notallowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('date_edited', models.DateTimeField(auto_now=True, verbose_name='date_edited')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('original_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddit_api.post')),
            ],
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('content', 'original_post', 'author'), name='sameComment_in_samePost_by_sameAuthor_notAllowed'),
        ),
    ]
